name: Build Kivy APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags
          clean: true     # Clean the repo before checking out

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specify the Python version required for Buildozer and Kivy

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openjdk-8-jdk unzip zlib1g-dev libncurses5:i386 libstdc++6:i386 libz1:i386 libbz2-1.0:i386 libstdc++6:i386 libncurses5:i386 libgtk2.0-0:i386 libpangox-1.0-0:i386 libpangoxft-1.0-0:i386 libidn11:i386 libglu1-mesa:i386 p7zip-full
          pip install --upgrade pip
          pip install buildozer cython

      - name: Cache Buildozer directories
        uses: actions/cache@v4
        with:
          path: |
            ~/.buildozer
            ~/.gradle
            ~/.android
          key: ${{ runner.os }}-buildozer-${{ hashFiles('**/buildozer.spec') }}

      - name: Initialize Buildozer
        run: |
          buildozer init
        working-directory: .  # Adjust if your buildozer.spec is in a subdirectory

      - name: Build APK
        run: |
          buildozer android debug
        working-directory: .  # Adjust if your buildozer.spec is in a subdirectory

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: kivy-app-apk
          path: bin/*.apk  # Path to your generated APK file(s)
