name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Change ownership of .git directory
        run: sudo chown -R $USER:$USER .git

      - name: Get Date
        id: get-date
        run: echo "date=$(date -u +%Y%m%d)" >> $GITHUB_ENV

      - name: Cache Buildozer global directory
        uses: actions/cache@v4
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - name: Cache Buildozer directory
        uses: actions/cache@v4
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ env.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        run: |
          buildozer android debug || (
            echo "Buildozer failed. Capturing log..." &&
            cp .buildozer/android/platform/build-arm64-v8a_armeabi-v7a/dists/[your-app]/buildozer.log buildozer.log &&
            cat buildozer.log &&
            exit 1
          )
        env:
          LC_ALL: en_US.UTF-8
        shell: bash

      - name: Upload Buildozer log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: buildozer-log
          path: buildozer.log

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk




